# Generated by Django 2.1 on 2018-12-30 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.Subdomain')),
            ],
        ),
    ]
