# Generated by Django 2.1 on 2018-12-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_auto_20181230_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='track',
            field=models.CharField(default='Algorithms', max_length=250),
        ),
    ]
