# Generated by Django 2.1.7 on 2019-12-26 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_auto_20190101_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Test Case Number')),
                ('input', models.TextField(max_length=2000, null=True, verbose_name='Test Case Input')),
                ('output', models.TextField(max_length=2000, null=True, verbose_name='Test Case Output')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(max_length=1000, null=True, verbose_name='I/O Explanation'),
        ),
        migrations.AddField(
            model_name='question',
            name='input_format',
            field=models.TextField(max_length=500, null=True, verbose_name='Expected Input'),
        ),
        migrations.AddField(
            model_name='question',
            name='output_format',
            field=models.TextField(max_length=500, null=True, verbose_name='Expected Output'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_body',
            field=models.TextField(max_length=500, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='question',
            name='sample_input',
            field=models.TextField(max_length=500, null=True, verbose_name='Sample Input Format'),
        ),
        migrations.AddField(
            model_name='question',
            name='sample_output',
            field=models.TextField(max_length=500, null=True, verbose_name='Sample Output Format'),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Question Title'),
        ),
        migrations.AddField(
            model_name='testcases',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.Question'),
        ),
    ]
